services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Docker/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        environment:
            - ENV=prod
        extra_hosts:
            # To make host.docker.internal work on Linux.
            - "host.docker.internal:host-gateway"

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Docker/Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        environment:
            - NODE_ENV=prod
            - VITE_APP_API_ENDPOINT=http://backend:8000/api
        depends_on:
            - backend
