services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - db/:data/postgres
        ports:
            - "5432:5432"

    backend:
        build:
            context: .
            dockerfile: ./backend/Docker/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        environment:
            - ENV=dev

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Docker/Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        environment:
            - NODE_ENV=dev
        depends_on:
            - backend
