services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Docker/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        environment:
            - ENV=prod
            - DB_HOST=host.docker.internal
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Docker/Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        environment:
            - NODE_ENV=prod
        depends_on:
            - backend
