services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Docker/Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./backend/.env
        environment:
            - ENV=dev

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Docker/Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - ./frontend/.env
        environment:
            - NODE_ENV=dev
        depends_on:
            - backend
