# Generated by Django 3.2.11 on 2022-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220106_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='num_upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='num_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='num_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
