# Generated by Django 3.2.11 on 2022-01-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='postvotes',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='vote_once_constraint'),
        ),
        migrations.AddConstraint(
            model_name='postvotes',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('upvote', True), _negated=True), models.Q(('downvote', True), _negated=True), _connector='OR'), name='cant_upvote_and_downvote'),
        ),
    ]
