# Generated by Django 4.2.7 on 2023-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSLambdaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_invocations', models.PositiveBigIntegerField(default=0)),
                ('last_invocation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
