name: Automated Tests

on: [push, pull_request]

env:
    SUBNET_ID_ONE: ${{secrets.SUBNET_ID_ONE}}
    SUBNET_ID_TWO: ${{secrets.SUBNET_ID_TWO}}
    SUBNET_ID_THREE: ${{secrets.SUBNET_ID_THREE}}
    RDS_SECURITY_GROUP_ID: ${{secrets.RDS_SECURITY_GROUP_ID}}
    SECRET_KEY: ${{secrets.SECRET_KEY}}
    DB_USER: ${{secrets.DB_USER}}
    DB_NAME: ${{secrets.DB_NAME}}
    DB_HOST: ${{secrets.DB_HOST}}
    DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    DB_PORT: ${{secrets.DB_PORT}}

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Upgrade pip
              run: |
                  python -m pip install --upgrade pip
            - name: Install dependencies
              working-directory: ./backend
              run: |
                  pip install -r requirements.txt
            - name: Run Tests
              working-directory: ./backend
              run: |
                  python manage.py makemigrations
                  python manage.py test --noinput --verbosity 2

    deploy:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Set Up Postgres
              run: |
                  sudo systemctl start postgresql.service
            - name: Upgrade pip
              run: |
                  python -m pip install --upgrade pip
            - name: Install dependencies
              working-directory: ./backend
              run: |
                  pip install -r requirements.txt
            - name: Install pipenv and virtual environment dependencies so we can run zappa deploy command
              working-directory: ./backend
              run: |
                  pip install pipenv
                  pipenv install
            - name: Set Up Zappa Settings
              working-directory: ./backend
              run: |
                  ./create-zappa-settings-from-github-actions.sh
            - name: Set Up AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
                  aws-region: ap-southeast-2
            - name: Deploy With Zappa
              working-directory: ./backend
              run: |
                  echo "$${env.SECRET_KEY}"
                  pipenv run python manage.py collectstatic
                  pipenv run zappa update dev
