name: Tests and Deply

on: [push, pull_request]

env:
    SECRET_KEY: ${{secrets.SECRET_KEY}}

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Upgrade pip
              run: |
                  python -m pip install --upgrade pip
            - name: Install dependencies
              working-directory: ./backend
              run: |
                  pip install -r requirements.txt
            - name: Run Tests
              working-directory: ./backend
              run: |
                  export ENV=dev
                  python manage.py makemigrations
                  python manage.py test --noinput --verbosity 2

    deploy:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: SSH into VM and Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: 209.38.22.34
                  username: root
                  key: ${{secrets.SERVER_PRIVATE_KEY}}
                  script: |
                      cd /usr/local/src/django-react-reddit-clone
                      git checkout main
                      git pull
                      docker-compose -f docker-compose.prod.yml up --build -d
