name: Automated Tests

on: [push, pull_request]

env:
    SECRET_KEY: ${{secrets.SECRET_KEY}}
    DB_USER: ${{secrets.DB_USER}}
    DB_NAME: ${{secrets.DB_NAME}}
    DB_HOST: ${{secrets.DB_HOST}}
    DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    DB_PORT: ${{secrets.DB_PORT}}

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Upgrade pip
              run: |
                  python -m pip install --upgrade pip
            - name: Install dependencies
              working-directory: ./backend
              run: |
                  pip install -r requirements.txt
            - name: Run Tests
              working-directory: ./backend
              run: |
                  export ENV=dev
                  python manage.py makemigrations
                  python manage.py test --noinput --verbosity 2
